# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-23 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import filter.models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=filter.models.upload_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to=filter.models.upload_location),
        ),
    ]
