# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 19:08
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import filter.models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=filter.models.upload_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='qr',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=filter.models.upload_location),
        ),
    ]
